gmail_uname="kalikaenterprises@gmail.com"
#gmail_pwd="pkrr waub dtgl jmmp"
gmail_pwd="bake syvp gxfm xhtv"  ## name of app KaliRAG

[aws]
access_key_id = "your_access_key_id"
secret_access_key = "your_secret_access_key"
bucket_name = "your_s3_bucket_name"
